export const options = [
  { id: "trade1", name: "Construction & Remodeling" },
  { id: "trade2", name: "Tile Works, Kitchen & Bathrooms" },
  { id: "trade3", name: "Concrete, Masonry & Foundations" },
  { id: "trade4", name: "Landscape" },
  { id: "trade5", name: "Earthworks, Drives & Parking Lots" },
  { id: "trade6", name: "Roofing & Solar" },
  { id: "trade7", name: "Gutters, Siding & Fencing" },
  { id: "trade8", name: "Water/Fire & Mold Remediation" },
  { id: "trade9", name: "Electrical & Low Voltage" },
  { id: "trade10", name: "Plumbing (all Facets)" },
  { id: "trade11", name: "HVAC" },
  { id: "trade12", name: "Carpentry & Finish Carpentry" },
  { id: "trade13", name: "Cabinets, Countertops & Furniture" },
  { id: "trade14", name: "Decks, Pergolas & Gazzebo" },
  { id: "trade15", name: "Flooring - All Types" },
  { id: "trade16", name: "Painting & Staining" },
  { id: "trade17", name: "Drywall Install & Repair Mud Texture" },
  { id: "trade18", name: "Garage & Garage Doors" },
  { id: "trade19", name: "Cleaning Services & Junk Haul Off" },
  { id: "trade20", name: "Glass, Mirrors, Windows & Doors" },
  { id: "trade21", name: "Metal Fab, Fireplaces" },
  { id: "trade22", name: "Handyman Services" },
  { id: "trade23", name: "Architectural, Engineering & Law" },
  { id: "trade24", name: "Supplier & Advertiser (all trades)" },
];
export const stateList = [
  "Alabama",
  "Alaska",
  "American Samoa",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "District of Columbia",
  "Federated States of Micronesia",
  "Florida",
  "Georgia",
  "Guam",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Marshall Islands",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Northern Mariana Islands",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Palau",
  "Pennsylvania",
  "Puerto Rico",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virgin Island",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];
export const templateList = [
  "Template 1",
  "Template 2",
  "Template 3",
  "Template 4",
  "Template 5",
];
export const colorSchemeList = [
  { text: "Color 1", color: "#fff" },
  { text: "Color 1", color: "red" },
  { text: "Color 3", color: "blue" },
];
